### ISSUE TITLE
Major stopword differences with "natural" package (inaccurate data?)

### ISSUE THREAD

**Issue by titanism** [fergiemcdowall/stopword#286]
Cross-posting here this reference for you to look at @fergiemcdowall in case anything stands out to you.

Ref: https://github.com/NaturalNode/natural/issues/651

**Comment by fergiemcdowall** [comment]
@titanism what are the objectives and expectations here? Maybe a bit of background?

**Comment by eklem** [comment]
I saw that some of the difference is numbers as digits. Since Unicode property escapes came we've moved to only having words or numbers as words since the extraction of words are now far better, no matter which alphabet. I've made a library to not have to do the actual regex'es all the time: [`words-n-numbers`](https://github.com/eklem/words-n-numbers)

And we're not removing punctuation with the stopword library for the same reason. For people that would still need to remove digits (0-9), I've added a digits only "language".

If `stopword` can be used in `natural`, that would be really nice, but I'm not sure if I fully agree that stopwords are a fixed size for a given language. The lists I generate my self I keep sorted by frequency, and try to keep the lists somewhat long. This way, you can cut off the list to make the stopword removal less agressive.

Anyway, interested in discussing the differences further. What do you think, @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
> Stopwords should be pretty standard, and not so much opinionated

Agree in principle. Who should decide what words make the list and how should they decide?

 > It would be awesome if natural actually used stopword under the hood perhaps

That would be great, and they are free to do so 🙂👍

 > Maybe we can make these packages 1:1 with each other?

Its not something that this project is aiming for at the moment. In any case the best way to achieve this would be for ’natural’ to depend on ’stopword’.

**Comment by eklem** [comment]
For the places where you think there are clear shortages in one of our language stopword list, I'll add them to our lists.

**Comment by eklem** [comment]
I'm subscribing to [the issue over at Natural](https://github.com/NaturalNode/natural/issues/651), so closing this issue for now. Feel free to open it agaian if anything happens. I'll also open it if there are some actionable events.
