### ISSUE TITLE
put each word in a single line?

### ISSUE THREAD

**Issue by WebMechanic** [fergiemcdowall/stopword#300]
Hello,

I'm interested in using search-index for our (local) documentation project and eventually ended up here.

Looking through some of the language files I found a couple of conjugations missing for the languages I'm interested in.
It's hard to add them an create a PR without the risk of causing merge conflicts if everything's literally in a single line.

I therefore suggest to reformat all language files and have each single word in its own line. 

This should add virtually nothing to the file size if "comma space" (`,\s`) is replaced with "comma line-feed" (`,\n`). This could possibly be automated once in batch with tools like Prettier or ESlint autofix or a global search/replace in any decent Unicode aware code editor.

Having words in separate line would also simplify adding possible new candidates (languages evolve) that always have a butt load of conjugations.

Thanks for considering.

**Comment by eklem** [comment]
I'll look into that. It will add a little, since you have indenting on each line. But that doesn't matter since we will still bundle/build minified versions. Thanks for the input.

**Comment by eklem** [comment]
Apologies for the long wait, @WebMechanic. Fixed in latest commit and published to NPM under v2.0.6.
If you have any small or big edits, they are most welcome! And thanks for the issue created.

https://github.com/fergiemcdowall/stopword/commit/00044a34e47491f86a3874bffe6390e5977ab74b
https://github.com/fergiemcdowall/stopword/releases/tag/v2.0.6
